name: Docker Push & re-deploy Fluffy

on:
  push:
    branches: [ master ]
    
    
env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}
  IMAGE_NAME_DOCKER_HUB: snicki13/fluffy

jobs:
  docker:
    name: Publish - Docker Hub
    runs-on: ubuntu-18.04
    permissions:
      contents: read
      packages: write
      
    steps:
      - uses: actions/checkout@v1
      
      - name: Login to Docker Hub
        run: docker login -u ${{ secrets.DOCKER_USER }} 
             -p ${{ secrets.DOCKER_PASS }}
        
      - name: Log into registry ${{ env.REGISTRY }}
        uses: docker/login-action@v1.10.0
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1.5.1

      - name: Extract Docker metadata
        id: meta
        uses: docker/metadata-action@v3.5.0
        with:
          images: ${{ env.IMAGE_NAME_DOCKER_HUB }}, ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
      - name: Build and push Docker image
        uses: docker/build-push-action@v2.7.0
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          builder: ${{ steps.buildx.outputs.name }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

  deploy:
    name: Redeploy testsystem
    runs-on: ubuntu-latest
    needs: docker
    steps:
    - name: Redeploy testsystem via ssh.
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.DEPLOY_HOST }}
        username: ${{ secrets.DEPLOY_USER }}
        key: ${{ secrets.DEPLOY_PRIV_KEY }}
        script: dist/restart-fluffy.sh
